# -*- coding: utf-8 -*-
"""spacy_flask_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkDe1Ok57ZP49YLiGSZXekynUxVjeZq4
"""

from flask import Flask,render_template,url_for,request,jsonify
import re
import pandas as pd
import spacy
from spacy import displacy
import en_core_web_sm
import spacy
import scispacy
nlp = spacy.load("en_ner_bc5cdr_md")
#nlp = spacy.load('en_ner_bc5cdr_md')

app = Flask(__name__)

#!pip install scispacy
#!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_ner_bc5cdr_md-0.2.4.tar.gz

@app.route('/')
def health_check():
	return '200'

@app.route('/get_entities',methods=["POST"])
def extract_entities():
  if request.method=='POST':
    data = request.json
    text=data['data']
    doc = nlp(text)
    entities=doc.ents
    entities_=[str(x) for x in entities]
    return jsonify({'output':entities_})


if __name__ == '__main__':
	app.run(debug=True)


