# -*- coding: utf-8 -*-
"""spacy_flask_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkDe1Ok57ZP49YLiGSZXekynUxVjeZq4
"""

from flask import Flask,render_template,url_for,request
import re
import pandas as pd
import spacy
from spacy import displacy
import en_core_web_sm
#nlp = spacy.load('en_ner_bc5cdr_md')

app = Flask(__name__)

#!pip install scispacy
#!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_ner_bc5cdr_md-0.2.4.tar.gz

@app.route('/')
def health_check():
	return '200'

@app.route('/get_entities',methods=["POST"])
def extract_entities():
  if request.method=='POST':
    #print(request.data)
    data = request.json
    text=data['data']
    import spacy
    import scispacy
    nlp = spacy.load("en_ner_bc5cdr_md")
    doc = nlp(text)
    #print('sentences of the text')
    #print(list(doc.sents))
    #print('Entities')
    print(list(doc.ents))
    return 'success'


if __name__ == '__main__':
	app.run(debug=True)


